Refactor: Simplify Send Notification Interface
hyperjumptech/monika pull request #1019
Opened 2023-03-24 07:41 UTC by haricnugraha

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
Reduce sendNotification function complexity. As a part of the effort to solve issue #990.

## How did you implement / how did you fix it  
1. Re-enable Eslint complexity rule
2. Make the send notification validator and send function consistent
3. Remove manual validation. Currently, there are 3 validation for notification config. Manual, using joi, and json schema. 
4. Add some tests

## How to test  
1. Run unit test
2. Run Monika as usual

2023-03-28 07:44 UTC, nicnocquee requested changes
I think we need to update the doc on how to add new notification channel https://monika.hyperjump.tech/guides/new-notifications

2023-03-28 08:26 UTC, sapiderman commented
> I think we need to update the doc on how to add new notification channel https://monika.hyperjump.tech/guides/new-notifications

agree but this PR is already soo big, better make it in another PR?

2023-03-28 11:06 UTC, sapiderman approved these changes
pheeew! Works for me!
😅   💦

2023-03-31 07:39 UTC, nicnocquee approved these changes

2023-03-31 07:39 UTC, merged