Clean error msg when failed to load config file
hyperjumptech/monika pull request #1057
Opened 2023-06-10 09:58 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Addresses issue #1036 
2. Cleans up error message when config failed to be loaded

## How did you implement / how did you fix it  
1.  Catch the thrown error
2. Exit the program when not in symonMode, 

## How to test  
1. Use a bad formatted config.yaml 
```yaml
probes:
  - id: 'http-1'
    name: 'status-200-test'
    requests:
      urlsdfsd: https://httpbin.org/status/404
    alerts:
      - assertion: response.status < 200 or response.status > 299
        message: HTTP Status is not 200
      - assertion: response.time > 2000
        message: Response time is more than 2000ms
    incidentThreshold: 3
    recoveryThreshold: 3

notifications:
  - id: desktop
    type: desktop
```

## Before PR

Dev type error
![image](https://github.com/hyperjumptech/monika/assets/964106/a8359be9-33f3-4ee2-b32a-4e0b98a7f74f)

## After PR

Cleaned up error message
![image](https://github.com/hyperjumptech/monika/assets/964106/70b471af-012a-4066-baa5-b017ea5f0262)

2023-06-19 08:28 UTC, haricnugraha requested changes

2023-06-19 08:28 UTC, haricnugraha commented on src/components/config/validate.ts
> +// const hasConfig = flags.config.length > 0
Please remove the dead code

2023-06-19 08:28 UTC, haricnugraha commented on src/components/config/validate.ts
> +  // const { flags } = getContext()
Please remove the dead code

2023-06-19 08:28 UTC, haricnugraha commented on src/components/config/validate.ts
> +  // const hasConfig = flags.config.length > 0
Please remove the dead code

2023-06-30 07:13 UTC, haricnugraha approved these changes

2023-06-30 07:38 UTC, dennypradipta approved these changes

2023-06-30 08:24 UTC, merged