Update to Node to v20.x
hyperjumptech/monika pull request #1235
Opened 2024-02-05 00:47 UTC by sapiderman

# Monika Pull Request (PR)

## What feature/issue does this PR add

1. Implements #1234 
2. Updating node to v20

## How did you implement / how did you fix it

1. Update all pipelines
2. 

## How to test

1. Pushing the branch here first to test the pipelines.
2. `npm run test` should all work without errors

2024-02-06 04:31 UTC, dennypradipta requested changes
A little request changes.

2024-02-06 04:31 UTC, dennypradipta commented on package.json
In the 'engines' key, you need to update the node to be 20.x too

2024-02-06 06:03 UTC, sapiderman commented on package.json
got it...good catch thanks!

2024-02-12 06:02 UTC, haricnugraha approved these changes

2024-02-12 07:35 UTC, dennypradipta approved these changes
Nicely done.

2024-02-12 07:39 UTC, merged