Remove axios package
hyperjumptech/monika pull request #1314
Opened 2024-07-19 07:19 UTC by irwansyahwii

# Monika Pull Request (PR)

## What feature/issue does this PR add

1.

## How did you implement / how did you fix it

1.

## How to test

1.
2.
3.

2024-08-04 01:49 UTC, suyono3484 requested changes
Hi @irwansyahwii, could you double check the test result? I ran the test locally and it failed. You can run the test locally by running

```shell
npm run test
``` 

One of the failed test is `src/components/probe/prober/http/request.test.ts`. You can run the failed test specifically by using 

```shell
mocha --config .mocharc.json --forbid-only src/components/probe/prober/http/request.test.ts
```

I think the failed tests are blocking the github checks.

2024-08-08 05:30 UTC, irwansyahwii commented
> Hi @irwansyahwii, could you double check the test result? I ran the test locally and it failed. You can run the test locally by running
> 
> ```shell
> npm run test
> ```
> 
> One of the failed test is `src/components/probe/prober/http/request.test.ts`. You can run the failed test specifically by using
> 
> ```shell
> mocha --config .mocharc.json --forbid-only src/components/probe/prober/http/request.test.ts
> ```
> 
> I think the failed tests are blocking the github checks.

ok will do

2024-08-08 07:08 UTC, irwansyahwii commented
> > Hi @irwansyahwii, could you double check the test result? I ran the test locally and it failed. You can run the test locally by running
> > ```shell
> > npm run test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > One of the failed test is `src/components/probe/prober/http/request.test.ts`. You can run the failed test specifically by using
> > ```shell
> > mocha --config .mocharc.json --forbid-only src/components/probe/prober/http/request.test.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the failed tests are blocking the github checks.
> 
> ok will do

Fixed

2024-08-12 11:55 UTC, irwansyahwii commented
The automated tests are not reliable. Sometimes it failed sometimes it succeed. Seems like there will be big architectural changes to fix it.

2025-02-14 10:18 UTC, sapiderman approved these changes
@irwansyahwii  this is good work, thanks for your contribution 🥇 🏆 🎖️ . 


Please resolve the conflicts, should be good to go!

2025-03-14 06:41 UTC, haricnugraha commented
Thank you for your contribution. I will close this pull request since there are no updates and the issue has been resolved. Feel free to re-open if needed.

2025-03-14 06:41 UTC, closed without merging