Issue/136 example docs
hyperjumptech/monika pull request #152
Opened 2021-04-19 09:16 UTC by dennypradipta

This PR resolves #136 which is to create an "Examples" section in the docs

2021-04-19 10:29 UTC, nicnocquee requested changes

2021-04-19 10:29 UTC, nicnocquee commented on docs/src/pages/guides/examples.md
> +In the configuration above, the first request will execute fetch all users available. If there are no triggered alerts, the response returned from the first request is ready to be used by the second
In the configuration above, the first request will fetch all users from `https://reqres.in/api/users`.  Then in the second request, Monika will fetch the details of the first user from the first request. If there are no triggered alerts, the response returned from the first request is ready to be used by the second request using values from `{{ responses.[0].data }}`.

Let's say the response from fetching all users in JSON format as follows:

2021-04-19 10:29 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +Details of the field are give in the table below.
Details of the fields are shown in the table below.

2021-04-19 10:29 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +| headers    | Response headers from the URL requested (e.g SetCookie, ETag, etc.)      |
Response headers from the fetched request (e.g SetCookie, ETag, etc.).

2021-04-20 02:50 UTC, dennypradipta commented
Thank you @nicnocquee for the thorough review. I have updated the PR :grinning:

2021-04-20 08:05 UTC, nicnocquee approved these changes

2021-04-20 08:09 UTC, armedi approved these changes

2021-04-20 08:28 UTC, sapiderman approved these changes
looks good!

2021-04-20 08:28 UTC, sapiderman commented on docs/src/pages/guides/examples.md
> +By default if you didn't define the method, it will be set as GET. Please note that with this configuration, you will not get any notifications when github.com is down since the notifications configu
since the notification configuration is not defined. (singular)

2021-04-20 08:28 UTC, sapiderman commented on docs/src/pages/guides/examples.md
> +If there is a case where executing GET request to `https://github.com` triggered an alert, the next request will not be executed.
trigger**s** an alert. (soalnya pakai "is" di awal kalimat)

2021-04-20 08:28 UTC, sapiderman commented on docs/src/pages/guides/examples.md
> +Monika supports requests chaining, which enables you to do multiple request and use previous request(s) response for other request. For example, after executing a GET request to certain API, the next
Monika supports request chaining, which enables you to do multiple requests and the ability to use past responses from earlier requests. (s for tenses + compunds IS a pain in the ass)

2021-04-20 09:40 UTC, merged