Update overview.md
hyperjumptech/monika pull request #160
Opened 2021-04-22 05:15 UTC by ariawan

2021-04-22 05:53 UTC, sapiderman approved these changes
lgtm

2021-04-22 06:54 UTC, nicnocquee requested changes

2021-04-22 06:54 UTC, nicnocquee commented on docs/src/pages/overview.md
> +Monika operates by reading everything from a config file. Based on the configuration it will build and send out http requests. If the request response is not as expected, Monika will create an alert.
then can be sent via various notification channels

2021-04-23 07:17 UTC, nicnocquee approved these changes

2021-04-23 07:17 UTC, merged