feat: add all data into logs
hyperjumptech/monika pull request #163
Opened 2021-04-23 05:57 UTC by sapiderman

##PR 

### What this PR  fixes

Implement issue #131 : show and record response length

### Implementations

1. save to logs more data, requests and responses
2. move looper to top of directory
3. refactor saving to sqlite database
4. redo sql calls to sqlite
5. remap log data to db

2021-04-26 08:11 UTC, nicnocquee requested changes

2021-04-26 08:11 UTC, nicnocquee commented on src/components/logger/history.ts
> +  respErr: string
change the names to the full words, e.g., `respTime` -> `responseTime`

2021-04-28 08:32 UTC, nicnocquee approved these changes

2021-04-28 13:09 UTC, haricnugraha approved these changes

2021-04-28 13:09 UTC, merged