Add documentation on how to run on windows
hyperjumptech/monika pull request #176
Opened 2021-05-04 09:42 UTC by ilmiawan

Fix issue #170 on error when running monika on windows using `npm start`

## How this PR fix the issue
by adding information to the documentation on how to run manually on windows. 
instead of calling `npm start` windows users should run `.\bin\run`

## How to test 
open the documentation and follow the instruction to run on windows.

2021-05-04 14:09 UTC, nicnocquee requested changes
Wait, where is the change? 😄 

There is only binary change here.

2021-05-05 09:19 UTC, nicnocquee requested changes

2021-05-05 09:19 UTC, nicnocquee commented on README.md
> +- on linux/unix
on Linux/Unix/Mac

2021-05-05 09:30 UTC, ilmiawan commented on README.md
> +- on linux/unix
done

2021-05-05 09:31 UTC, nicnocquee approved these changes

2021-05-05 09:33 UTC, sapiderman approved these changes

2021-05-05 10:37 UTC, merged