feat: add repeats and custom id sequesnce
hyperjumptech/monika pull request #182
Opened 2021-05-09 17:45 UTC by sapiderman

## PR

### What this PR does
Implements #147 to add run options
1. Added -r  --repeat flag
2. Added -i  --id flag   

### Implementation 
1. Added an id feeder to handle user specified probe.id sequences
2. Added counter checking for repeat control

## How to test
1. Running `monika` or `bin/run` should work normally
2. `monika -r x` where x is any number, shoull repeat just x times
3. `monika -i 1,2,3` should run probe id 1, 2 and then 3. Sequence can be any valid id sequence (ex: 1,2,3 or 3,2,1 or 1,2,1) 
4. `monika -r 3 -i 1,2` should run probe id 1 and 2 repeating 3 times

2021-05-10 02:32 UTC, armedi requested changes

2021-05-10 02:32 UTC, armedi commented on src/index.ts
> +    'monika --1ogs',
```suggestion
    'monika --logs',
```

2021-05-10 02:32 UTC, armedi commented on src/index.ts
> +        idFeeder(config, Number(flags.repeat), flags.id)
when abortCurrentLooper is removed, monika will not be able to update it's configuration if new configuration is received from Symon

2021-05-10 07:41 UTC, armedi requested changes

2021-05-10 07:41 UTC, armedi commented on src/looper.ts
> +let isAborted = false
moving this variable to global scope will cause the value of isAborted to stay `true` after it's first set to true. 

This means that when monika receive new configuration from Symon, it clear probe interval from the previous configuration and the new interval for the new configuration will also get aborted immediately. Or in other word, the next configurations will never run.

2021-05-17 08:17 UTC, dennypradipta commented
It seems like that some iteration did not run the probe according to the order:

1. Running with `./run -r 3`
![image](https://user-images.githubusercontent.com/16670475/118454619-c5c93100-b722-11eb-92f6-d3cb3bf05655.png)

In the first iteration it is being run using the correct order: 1,2,3. In the second iteration, it is being run in wrong order: 3,1,2

2. Running with `./run -3 -i 1,2`
![image](https://user-images.githubusercontent.com/16670475/118454751-e8f3e080-b722-11eb-84f1-05ab9ceecf03.png)

In the first iteration it is being run using the wrong order: 2,1. In the second iteration, it is being run in correct order: 1,2

2021-05-18 08:39 UTC, nicnocquee approved these changes

2021-05-18 08:39 UTC, nicnocquee commented on src/looper.ts
> +    const idSplit = ids.split(',')
need to trim the elements

2021-05-18 09:25 UTC, armedi approved these changes

2021-05-19 08:05 UTC, merged