Fix links' visibility, improve how-to
hyperjumptech/monika pull request #205
Opened 2021-05-28 08:17 UTC by samsunoor

- Fix broken link and link visibility issues on Quick Start
- Improve how-to
- Minor corrections

2021-05-28 08:44 UTC, nicnocquee requested changes

2021-05-28 08:44 UTC, nicnocquee commented on docs/src/pages/guides/notifications.md
> +   1. If you have activated 2-Factor-Authentication (2FA), you need to <a className="text-blue-700 font-semibold" href="https://support.google.com/accounts/answer/185833">create an App Password from
don't use the styling for link. we will change the styles later when we revamp the landing page and doc

2021-05-31 05:45 UTC, sapiderman approved these changes
looks ok

2021-05-31 08:30 UTC, gsukanto approved these changes

2021-05-31 08:33 UTC, nicnocquee approved these changes

2021-05-31 08:33 UTC, armedi approved these changes

2021-05-31 08:34 UTC, merged