Fixed(docs): add monika whatsapp notifier documentation
hyperjumptech/monika pull request #209
Opened 2021-05-31 19:28 UTC by ilmiawan

#monika PR
fix #178 
## What issue this PR is trying to solve?
Currently there is no documentation available for implementing Monika Whatsapp Notifier in Monika.
## How this PR solve the issue?
By adding Monika Whatsapp Notifier implementation document on Monika Notification page and
add CTA in landing page.
## How to test
- Build Monika
- run Monika
- access monika landing page and notification guide page

2021-06-01 03:31 UTC, sapiderman approved these changes
Doc **ONLY** changes are ok.  
Note: But included in this PR are the source changes from PR #207. I would separate the two PR as merging this will auto merge the #207 also. So merge this only after 207.

2021-06-02 08:05 UTC, nicnocquee requested changes

2021-06-02 08:05 UTC, nicnocquee commented on docs/src/pages/index.js
> +                      Microsoft Teams!
can delete this "More notification channels are coming including Microsoft Teams!"

2021-06-02 08:06 UTC, nicnocquee commented on docs/src/pages/guides/notifications.md
> +## Monika Whatsapp Notifier
add (COMING SOON)

2021-06-02 08:06 UTC, nicnocquee requested changes

2021-06-02 08:06 UTC, nicnocquee commented on docs/src/pages/guides/notifications.md
> +Monika now have its own notification channel, sent through your whatsapp number. To enable notification via Monika Whatsapp Notifier, you must create a Monika Notifier account first. Please consult [
remove the link to notifier. we will use proper domain later.

2021-06-02 08:15 UTC, nicnocquee approved these changes

2021-06-02 08:15 UTC, merged