added: Docs: Monika Whatsapp Notifier information
hyperjumptech/monika pull request #221
Opened 2021-06-11 18:54 UTC by nicnocquee

This PR adds information about Monika Whatsapp Notifier to the docs and the landing page.

2021-06-11 22:49 UTC, ilmiawan approved these changes

2021-06-14 08:16 UTC, dennypradipta approved these changes

2021-06-14 08:17 UTC, sapiderman requested changes
minor grammar.

2021-06-14 08:17 UTC, sapiderman commented on docs/src/pages/guides/notifications.md
> +You can get a Monika's alert notification to your Whatsapp number without having a Whatsapp Business account. First, you must create a [Monika Whatsapp Notifier account](https://whatsapp.hyperjump.te
minor typo:
"You can get a Monika alert..."

2021-06-14 08:17 UTC, armedi approved these changes

2021-06-14 08:20 UTC, sapiderman approved these changes

2021-06-14 08:24 UTC, merged