docs: revamp design
hyperjumptech/monika pull request #236
Opened 2021-06-21 10:19 UTC by samsunoor

This PR resolves #181 
## How to test
1. Open file `docs/src/libs/docs/md-loader.js`
2. Change line 10 to `const layout = data.layout || 'DocsNtmy'`
3. Move to terminal
4. `cd ./docs`
5. `npm run dev`
6. Visit any documentation page, e.g., `localhost:3000/overview`
7. Need to test mobile version visuals, too

2021-06-22 03:09 UTC, kevinhermawan commented on docs/src/components/Button.js
> +      } ${isRounded ? 'rounded-full' : 'rounded-md'}`}
You don't need to declare constant, just use `props.rounded`.

2021-06-22 03:09 UTC, kevinhermawan commented on docs/src/components/Button.js
> +      } ${isRounded ? 'rounded-full' : 'rounded-md'}`}
This too

2021-06-23 08:26 UTC, kevinhermawan approved these changes

2021-06-23 12:13 UTC, sapiderman approved these changes
works!

2021-06-24 10:04 UTC, raosan requested changes
as all component has been implemented, we can replace the original component and using the ntmy component so we can check without changing md-loader.js

2021-06-24 10:04 UTC, raosan commented on docs/src/components/LayoutDocsNtmy.js
> +                    <SidebarRoutes routes={routes} />
there is a warning in developer console saying there are duplicate keys
<img width="1141" alt="Screen Shot 2021-06-24 at 16 59 19" src="https://user-images.githubusercontent.com/5974862/123243908-a38ab600-d50d-11eb-83d3-bced3c22f3f9.png">

2021-06-24 12:49 UTC, raosan approved these changes

2021-06-24 12:49 UTC, merged