Responsive mobile home page
hyperjumptech/monika pull request #252
Opened 2021-06-25 04:41 UTC by samsunoor

This PR resolves #249 
### How did you implement
1. hide world-dot png on small screens
2. adapt video iframe size on small screens
3. adapt flex containers to column on small screens
  - get started & star button
  - footer
4. center text besides video on small screens
5. move `index-ntmy.js` to be `index.js`

### How to test
1. `cd docs`
2. `npm run dev`
3. Check mobile responsive on `localhost:3000`

2021-06-25 07:50 UTC, dennypradipta requested changes
![image](https://user-images.githubusercontent.com/16670475/123390025-adbbbb80-d5c4-11eb-9c33-d08478dd3a1a.png)
Is this expected behavior?

2021-06-25 07:52 UTC, dennypradipta requested changes
![image](https://user-images.githubusercontent.com/16670475/123390284-efe4fd00-d5c4-11eb-8a90-5dc48039f9f2.png)

I think the h1 needs a text-3xl class only for mobiles because it's too big, and maybe some minus margin top? Because it has a lot of spaces above the text

![image](https://user-images.githubusercontent.com/16670475/123390203-d9d73c80-d5c4-11eb-9715-705a7972fac9.png)

Here is the text with 3xl

2021-06-25 08:55 UTC, dennypradipta approved these changes

2021-06-28 03:28 UTC, raosan approved these changes

2021-06-28 03:28 UTC, merged