Cleanup log display in comand line (CLI)
hyperjumptech/monika pull request #262
Opened 2021-07-01 10:28 UTC by sapiderman

## PR
 Cleanup the log displays

## Implementation
1. Remove logs from event listener since it doesn't have actual function yet.
2. Closing [261](https://github.com/hyperjumptech/monika/issues/261)

## How to test
1. run monika from source (bin/run)

2021-07-01 20:41 UTC, nicnocquee requested changes

2021-07-01 20:41 UTC, nicnocquee commented on src/index.ts
> -// Subscribe FirstEvent
maybe just keep the listeners but remove the log.info so that in the future we just need to fill the functions.

2021-07-02 11:21 UTC, dennypradipta requested changes

2021-07-02 11:21 UTC, dennypradipta commented on src/index.ts
> -  log.info('Monika Event: ' + data)
Just add //TODO in case there is future events on developing this IMO

2021-07-05 08:22 UTC, dennypradipta approved these changes

2021-07-05 08:57 UTC, nicnocquee approved these changes

2021-07-05 09:20 UTC, merged