Add cli documentations
hyperjumptech/monika pull request #298
Opened 2021-07-27 10:57 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Closes #292 
2. Adding documentation shortuct to sidebar

## How did you implement / how did you fix it  
1.  Add shortcut to manifest

## How to test  
1. clone the project
2. move tot he docs/nextjs directory `cd docs`
3. type `npm ci` then  `npm run dev`
4. point your browser to the local server
5. You should see the new sidebar

![image](https://user-images.githubusercontent.com/964106/127142836-1b08583e-11ff-4095-bdc7-025204e34c4e.png)

2021-07-27 13:52 UTC, nicnocquee requested changes
Seems like the page itself lacks a lot of information about the available flags. 

- [x] In "Configuration", should also mention that aside from path to the configuration file, it could also run using configuration from remote URL. Moreover, Monika will auto reload when the file (both local and remote) is changed.
- [x] In "Create Config", should also mention that it will open our config generator web app. And when it's accompanied with --har and --postman, it will convert the har file and postman file to monika config file respectively. When -o is specified, the config file will be written to the path specified.
- [x] Add information for --har flag.
- [x] Add information for --postman flag.

2021-07-29 06:28 UTC, gsukanto approved these changes

2021-08-02 07:33 UTC, raosan approved these changes

2021-08-02 08:53 UTC, nicnocquee requested changes

2021-08-02 08:53 UTC, nicnocquee commented on docs/src/pages/guides/cli-options.md
> +You can use the combination of --create-config and --har switches to convert the HAR files to monika.config.
use `flags` instead of `switches`

2021-08-02 09:28 UTC, sapiderman commented on docs/src/pages/guides/cli-options.md
> +You can use the combination of --create-config and --har switches to convert the HAR files to monika.config.
fixed.

2021-08-02 09:38 UTC, nicnocquee approved these changes

2021-08-02 09:38 UTC, merged