docs: alerts
hyperjumptech/monika pull request #30
Opened 2021-03-12 09:34 UTC by raosan

2021-03-12 10:04 UTC, nicnocquee requested changes

2021-03-12 10:04 UTC, nicnocquee commented on docs/src/pages/guides/alerts.md
> +
Let's add an example. `response-time-greater-than-1-s` means Monika will send notification if the response of the URL is received after 1 second.

2021-03-12 10:22 UTC, nicnocquee approved these changes

2021-03-14 23:04 UTC, haricnugraha approved these changes

2021-03-14 23:04 UTC, merged