Update Documentation with --force
hyperjumptech/monika pull request #312
Opened 2021-08-03 06:40 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Update missing docs to include `--force` and impolement 

## How did you implement / how did you fix it  
1.  add flag.force detection to `--flush` handler
2. add force documentation on cli-options.md

## How to test  
1. type: `bin/run --flush` should get Y/n confirmation
2. type: `bin --flush --force` should be flushed without confirmation

2021-08-03 06:52 UTC, nicnocquee requested changes

2021-08-03 06:52 UTC, nicnocquee commented on docs/src/pages/guides/cli-options.md
>  ```
since we're mentioning force in the section below, maybe better to mention that you can use force here too in create-config

2021-08-03 08:23 UTC, gsukanto approved these changes

2021-08-04 07:41 UTC, nicnocquee approved these changes

2021-08-04 07:41 UTC, merged