Added: Alert/Notification messages sent to Sendgrid channel
hyperjumptech/monika pull request #324
Opened 2021-08-06 08:36 UTC by raosan

# Monika Pull Request (PR)  
fix #323

## What feature/issue does this PR add  
1. implement sendgrid alert

## How did you implement / how did you fix it  
1. call function `sendSendgrid` in `src/components/notification/index.ts`

## How to test  
1.  run monika and make an incident on target URL
2. get alert notification with detailed info

2021-08-06 08:37 UTC, raosan commented
need @nicnocquee help to test

2021-08-09 06:43 UTC, gsukanto approved these changes

2021-08-09 07:46 UTC, armedi approved these changes

2021-08-09 21:26 UTC, nicnocquee requested changes
Seems like sendgrid changes the URL in the email body. (See my DM in Teams).

2021-08-12 12:11 UTC, sapiderman approved these changes

2021-08-13 05:02 UTC, dennypradipta approved these changes

2021-08-13 08:22 UTC, raosan commented
> Seems like sendgrid changes the URL in the email body. (See my DM in Teams).

fixed. please re check

2021-08-16 03:20 UTC, nicnocquee requested changes

2021-08-16 03:20 UTC, nicnocquee commented on src/components/notification/channel/sendgrid.ts
> +      : body.replace(/http/g, '<http>'),
The email looks weird with <https>. It's better to just use html instead:

```
   subject,
    html: body.replace(/\n/g, '<br/>'),
```

2021-08-16 03:22 UTC, nicnocquee commented
Please also update the documentation to include the `sender` key.

2021-08-19 07:23 UTC, nicnocquee approved these changes

2021-08-19 07:23 UTC, merged