feat: interval per-probe
hyperjumptech/monika pull request #43
Opened 2021-03-17 08:35 UTC by kevinhermawan

This PR fixes #25

2021-03-19 07:12 UTC, nicnocquee requested changes

2021-03-19 07:12 UTC, nicnocquee commented on src/utils/looper.ts
> +    }, (probe.interval ?? 0) * MILLISECONDS)
I think default value is better be 10 seconds. Please put the default value as const at the beginning of the file.

2021-03-19 07:12 UTC, nicnocquee commented on src/utils/looper.ts
> +      falseThreshold: probe.falseThreshold || 5,
Please put the default value as const at the top.

2021-03-19 07:12 UTC, nicnocquee commented on config.example.json
> +      "interval": 0,
Change the value in this example to 10.

2021-03-19 07:12 UTC, nicnocquee commented on docs/src/pages/quick-start.md
> +         "interval": 10,
Please add explanation about this interval in the docs.

2021-03-19 15:05 UTC, sapiderman approved these changes
looks good!

2021-03-20 00:29 UTC, dennypradipta approved these changes

2021-03-22 07:10 UTC, nicnocquee approved these changes

2021-03-22 07:10 UTC, merged