Feat: Add summary display
hyperjumptech/monika pull request #440
Opened 2021-09-24 07:50 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Implements issue #189 

## How did you implement / how did you fix it  
1.  Adds the --summary flag
2. On Monika start a `monika.pid` file is saved with some json data such as proccess id and start time
3. When summary is run, it will look at `monika.pid` and get some stats off that.

## How to test  
1. run monika
2. while monika is still running, start another terminal and type `bin\run --summary` (you have to be on the same cwd)

## Screenshot
![image](https://user-images.githubusercontent.com/964106/134638156-09cb1900-a926-4ddd-8775-1a4761bc36b0.png)

2021-09-24 07:57 UTC, gsukanto commented on src/jobs/summary-notification.ts
> +  duration -= numDays * 86400 // get the remaining hourse
`hours`

2021-09-24 07:58 UTC, gsukanto approved these changes

2021-09-24 08:08 UTC, sapiderman commented on src/jobs/summary-notification.ts
> +  duration -= numDays * 86400 // get the remaining hourse
oops. thanks!

2021-09-27 03:12 UTC, armedi commented on src/jobs/summary-notification.ts
> +      log.indo('trying to cleanup monika.pid, got err: ', err)
`log.info`?

2021-09-27 03:12 UTC, armedi commented on src/index.ts
> +      description: 'Display a summay of monika running stats',
```suggestion
      description: 'Display a summary of monika running stats',
```

2021-09-27 03:16 UTC, armedi commented
Monika does not quit after displaying stats. Is that expected?

2021-09-28 03:20 UTC, sapiderman commented
Yeah.. Summary tried to load up the same sequence to get the counts etc.. And it triggers the checking processes that we don't want. Refactoring. Thanks!

2021-09-28 22:30 UTC, nicnocquee requested changes
Adding to @armedi 's comment, `--summary` also doesn't terminate when error occurs:

```
INFO: Could not find the file: monika.pid. Monika is probably not running or ran from a diffent directory
ERROR: Summary notification: ENOENT: no such file or directory, open 'monika.pid'
```

It should exit after showing the error.

2021-09-29 05:47 UTC, sapiderman commented on src/jobs/summary-notification.ts
> +      log.indo('trying to cleanup monika.pid, got err: ', err)
oh fixed. thanks!

2021-09-29 05:49 UTC, sapiderman commented on src/index.ts
> +      description: 'Display a summay of monika running stats',
fixed. thanks

2021-09-29 05:54 UTC, sapiderman commented
> Adding to @armedi 's comment, `--summary` also doesn't terminate when error occurs:
> 
> ```
> INFO: Could not find the file: monika.pid. Monika is probably not running or ran from a diffent directory
> ERROR: Summary notification: ENOENT: no such file or directory, open 'monika.pid'
> ```
> 
> It should exit after showing the error.

fixed here
![image](https://user-images.githubusercontent.com/964106/135210939-6247cfed-4711-477e-825c-7f519d84b503.png)

2021-09-29 07:59 UTC, sapiderman commented
latest iteration looks like this:

![image](https://user-images.githubusercontent.com/964106/135227281-203ad3de-0669-48e9-bc84-cc61419c8536.png)

2021-09-30 10:32 UTC, armedi approved these changes

2021-10-04 06:35 UTC, dennypradipta approved these changes

2021-10-04 07:55 UTC, nicnocquee approved these changes

2021-10-04 07:55 UTC, merged