fix: config file update not detected
hyperjumptech/monika pull request #447
Opened 2021-09-28 06:55 UTC by armedi

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
fixes #441 
Monika does not reload because of a mistake in the version assignment to the updated config.

## How to test  
1. run monika with any config
2. update the config while monika is running
3. check the terminal, it should display something similar to
```sh
WARN: config file update detected
Restarting Monika. ...
```

2021-09-28 09:59 UTC, samsunoor approved these changes

2021-09-28 21:50 UTC, nicnocquee requested changes
Seems like this PR breaks the running monika from remote yml.

Try

npm run start -- -c <URL to monika.yml>

It's ok with remote JSON though.

2021-09-29 03:32 UTC, armedi commented
> Seems like this PR breaks the running monika from remote yml.
> 
> Try
> 
> npm run start -- -c
> 
> It's ok with remote JSON though.

I found that this issue is inherited from the main branch, should be resolved in a separate PR

2021-09-29 06:08 UTC, sapiderman approved these changes

2021-09-29 07:12 UTC, nicnocquee approved these changes

2021-09-29 07:12 UTC, merged