SymonCilent: Reporting issue
hyperjumptech/monika pull request #516
Opened 2021-11-01 08:51 UTC by kevinhermawan

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Solves #515

2021-11-01 09:47 UTC, nicnocquee requested changes

2021-11-01 09:47 UTC, nicnocquee commented on src/symon/index.ts
> +
let's make these two overridable using env vars.

2021-11-01 10:28 UTC, kevinhermawan commented on src/symon/index.ts
> +
Looks good!

2021-11-01 10:35 UTC, nicnocquee approved these changes

2021-11-02 03:26 UTC, samsunoor approved these changes

2021-11-02 07:35 UTC, merged