Feat-672/dingtalk-notification
hyperjumptech/monika pull request #673
Opened 2022-05-24 14:41 UTC by lukman7788

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Add support for dingtalk notification

## How did you implement / how did you fix it  
1. Create account on dingtalk
2. Register `robot` on dingtalk => for getting access_token
3. Add config pushover on monika.yml
4. Add `keyword` on dingtalk apps => `Monika` (case sensitive)
![image](https://user-images.githubusercontent.com/42835003/170061699-b0160e4a-cdc0-4826-a151-6a42a6fe6694.png)
![image](https://user-images.githubusercontent.com/42835003/170061874-9efb71bc-7b0f-4775-a783-9505725640ca.png)
Select created robot
![image](https://user-images.githubusercontent.com/42835003/170062190-b8f79116-90da-42fd-9cea-0b86025f905d.png)
Add keyword
![image](https://user-images.githubusercontent.com/42835003/170062376-deeec5b4-dc84-4948-bca2-51337f066285.png)

Test case:
1. Welcoming + Incident
![image](https://user-images.githubusercontent.com/42835003/170062810-1dedbac3-5429-4fa7-bcd8-0c992598ba31.png)

2. Report
![image](https://user-images.githubusercontent.com/42835003/170063032-651f69d9-6b31-44aa-b8d9-fc280696fd29.png)

3. Recovery
![image](https://user-images.githubusercontent.com/42835003/170063180-72eec285-ea19-4e69-a3db-ac6d90bc2600.png)

2022-05-24 17:05 UTC, nicnocquee requested changes
Please add in documentation as well.

2022-05-25 02:13 UTC, lukman7788 commented
> Please add in documentation as well.

updated
![image](https://user-images.githubusercontent.com/42835003/170164821-2b383c98-52e1-4fbc-9abe-6739d9e61de0.png)

2022-05-25 02:37 UTC, dennypradipta commented
In the screenshots provided above, were there any methods to render the HTML tag? The "Tweet this status" is broken when it rendered.

2022-05-25 05:12 UTC, lukman7788 commented
> In the screenshots provided above, were there any methods to render the HTML tag? The "Tweet this status" is broken when it rendered.

updated @dennypradipta 
![image](https://user-images.githubusercontent.com/42835003/170184591-fdf2a4f0-b604-45f5-b5fb-0143eb27c76c.png)

2022-05-25 06:55 UTC, nicnocquee approved these changes

2022-05-25 08:11 UTC, gsukanto commented on src/components/notification/channel/dingtalk.ts
> + * Copyright (c) 2021 Hyperjump Technology                                        *
the year should be 2022

2022-05-25 08:13 UTC, gsukanto approved these changes
lgtm

2022-05-25 11:52 UTC, sapiderman approved these changes
👍🏽 

🦥 🐨 🐼 🐻

2022-05-27 02:12 UTC, merged