Issue/674 nightly release
hyperjumptech/monika pull request #691
Opened 2022-06-08 07:25 UTC by dennypradipta

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
This PR fixes #674 

## How did you implement / how did you fix it  
1. Change the npm publish command according to the existing npm-publish.yml workflow
2. Add notifications for nightly release to Teams

## How to test  
N/A

2022-06-08 11:59 UTC, haricnugraha approved these changes

2022-06-09 05:46 UTC, sapiderman approved these changes

2022-06-09 07:12 UTC, nicnocquee requested changes

2022-06-09 07:12 UTC, nicnocquee commented on .github/workflows/nightly-release.yml
>        - name: 🐱 Create GitHub release
I think this will trigger the workflow in npm-publish.yml. Since it's a nightly release, we don't need to create a GitHub release for it.

2022-06-09 16:43 UTC, nicnocquee approved these changes

2022-06-09 16:43 UTC, merged