[748/refactor]: Reduce the height of the navigation header
hyperjumptech/monika pull request #749
Opened 2022-07-05 04:44 UTC by herenacreative

# Monika Pull Request (PR)  

## What feature/issue does this PR add  

#748 Landing page refinement 
1. Reduce the height of the navigation header.

## How did you implement / how did you fix it  

## How to test  
1.  Go to https://monika.hyperjump.tech

<img width="1436" alt="Screen Shot 2022-07-05 at 11 32 31" src="https://user-images.githubusercontent.com/47026826/177250707-842eaf62-0214-44db-8100-20afaf9d41e0.png">

2022-07-05 07:00 UTC, nicnocquee requested changes

2022-07-05 07:00 UTC, nicnocquee commented on docs/src/pages/index.js
> +                  notification when {'\n'}
please don't use new line `\n` here. It's better to change the width container instead so that the text is not polluted with unnecessary new lines.

2022-07-05 09:18 UTC, nicnocquee requested changes

2022-07-05 09:18 UTC, nicnocquee commented on docs/src/pages/index.js
> +                  </span>
Can we not do this? Keep the text plain and continuous without span and br, except for the `web app is down` text. To change the line height, I think you can use the `leading-x` class names from tailwind. Check out the doc [here](https://tailwindcss.com/docs/line-height).

2022-07-07 07:49 UTC, nicnocquee approved these changes

2022-07-12 02:58 UTC, sapiderman requested changes
Is this supposed to say "Start" or "Stars"

![image](https://user-images.githubusercontent.com/964106/178399029-5f7e4094-d87e-4db9-a39c-4de0eaeca251.png)

2022-07-12 06:48 UTC, nicnocquee commented
> Is this supposed to say "Start" or "Stars"
> 
> ![image](https://user-images.githubusercontent.com/964106/178399107-b08a9c26-b954-46a3-8edc-3de14c63ebf0.png)

Another thing @herenacreative can you please add a bit of spacing between the icon and the Stars text.

2022-07-13 08:01 UTC, sapiderman approved these changes
👍🏽 👍🏽 👍🏽

2022-07-13 08:21 UTC, merged