Improve documentation details
hyperjumptech/monika pull request #758
Opened 2022-07-07 03:16 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Found issues in notification channel examples

## How did you implement / how did you fix it  
1.  Fixed the notification examples, found some copy paste errors
2. Update Probes.md text, mentioning all the different requests.
3. Some grammar updates.

2022-07-07 07:54 UTC, nicnocquee requested changes

2022-07-07 07:54 UTC, nicnocquee commented on docs/src/pages/guides/examples.md
> +Monika supports request chaining, which enables you to do multiple requests and the ability to use past responses from earlier requests. For example, after executing a GET request to certain a API, t
a certain API

2022-07-07 07:54 UTC, nicnocquee commented on docs/src/pages/guides/notifications.md
> +4. Under Incoming webhook, click **Add another** if one already exists, in either case you need to provede a name.
provide

2022-07-08 02:42 UTC, sapiderman commented on docs/src/pages/guides/notifications.md
> +4. Under Incoming webhook, click **Add another** if one already exists, in either case you need to provede a name.
fixed. thanks.

2022-07-08 07:11 UTC, kevin-hyperjump approved these changes

2022-07-08 07:14 UTC, nicnocquee approved these changes

2022-07-08 07:16 UTC, merged