fix: TCP request doesn't make any request
hyperjumptech/monika pull request #784
Opened 2022-07-20 07:45 UTC by kevin-hyperjump

This PR fixes #783 and contains:

Simply, we should immediately end the connection after successfully connecting to the server to avoid a timeout error, because the `"data"` will not listen if `client.write` is not emitted.

2022-07-20 09:02 UTC, nicnocquee approved these changes

2022-07-21 03:24 UTC, sapiderman requested changes
Can we print out the TCP errors out to the console (through pino) like regular http errors when we get them. Otherwise how would users know they're getting errors?

2022-07-21 07:26 UTC, kevin-hyperjump commented
> Can we print out the TCP errors out to the console (through pino) like regular http errors when we get them. Otherwise how would users know they're getting errors?

The TCP error was handled by Promise rejection, I guess it will be printed too. If not, please create a new issue, I'll keep this PR only for fixing the bug :)

2022-07-21 08:10 UTC, sapiderman approved these changes

2022-07-21 08:11 UTC, sapiderman commented
> > Can we print out the TCP errors out to the console (through pino) like regular http errors when we get them. Otherwise how would users know they're getting errors?
> 
> The TCP error was handled by Promise rejection, I guess it will be printed too. If not, please create a new issue, I'll keep this PR only for fixing the bug :)

okay!

2022-07-21 09:49 UTC, merged