779/refactor: Request and response in verbose mode
hyperjumptech/monika pull request #844
Opened 2022-08-03 07:42 UTC by herenacreative

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. 779/refactor: Request and response in verbose mode

## How did you implement / how did you fix it  
1.  

## How to test  
1. npm run start --verbose

<img width="773" alt="Screen Shot 2022-08-03 at 14 27 38" src="https://user-images.githubusercontent.com/47026826/182552320-f46347a5-8a2c-429f-ba5a-7e88173eb6a4.png">

2022-08-09 05:21 UTC, sapiderman commented
@herenacreative 
Ok... im getting the request.. good.
Still not getting response though

![image](https://user-images.githubusercontent.com/964106/183570484-615afb6a-68aa-4bb9-b7e7-1129833ae014.png)

2022-08-10 07:49 UTC, nicnocquee requested changes
In verbose mode, user should be able to see what request was sent by Monika **every time it sends the request**, which includes the method, the URL, and the header (if any).

Seems like this PR doesn't show that information.

<img width="1069" alt="Screenshot 2022-08-10 at 09 47 56" src="https://user-images.githubusercontent.com/311343/183845290-a015e873-b37f-4ec1-bb15-15f32beff4d0.png">

2022-08-16 20:14 UTC, nicnocquee commented
@herenacreative still need to update the probes config, especially need to format it so that it's clear that there are multiple requests in a probe.

Currently,

```
Probes:
- Probe ID: 1
    Name: GitHub
    Description: Multiple
    Interval: 20
    Request Method: GET
    Request URL: https://github.com
    Request Headers: -
    Request Body: -
    Request Method: GET
    Request URL: https://github.com/hyperjump
    Request Headers: -
    Request Body: -
    Alerts: [{ "query": "response.status < 200 or response.status > 299", "message": "HTTP Status is not 200"},
            { "query": "response.time > 2000", "message": "Response time is more than 2000ms" }]
```

It's better to be,

```
Probes:
- Probe ID: 1
    Name: GitHub
    Description: Multiple
    Interval: 20
    Requests:
      - Request Method: GET
         Request URL: https://github.com
         Request Headers: -
         Request Body: -
      - Request Method: GET
         Request URL: https://github.com/hyperjump
         Request Headers: -
         Request Body: -
    Alerts: [{ "query": "response.status < 200 or response.status > 299", "message": "HTTP Status is not 200"},
            { "query": "response.time > 2000", "message": "Response time is more than 2000ms" }]
```

Also, format the alerts so that it doesn't look like JSON.

Basically, they should look like the YAML format.

2022-08-26 07:57 UTC, nicnocquee approved these changes

2022-08-27 04:19 UTC, sapiderman approved these changes
Small suggestion but looks ok otherwise. Good work!

2022-08-27 04:19 UTC, sapiderman commented on src/components/logger/request-log.ts
> +      Request Body:
Suggestion:  Put hese in one line, more compact and easier to read imho
```javascript
Request Headers: $(JSON.stringify(this.request?headers) || '-'}
```

Then the key and value are in one line:
![image](https://user-images.githubusercontent.com/964106/187014010-b4dee351-c4f3-4aaf-b7ab-c4e7d7342b50.png)

vs

![image](https://user-images.githubusercontent.com/964106/187013952-9c5b80b5-ac87-4e1a-b922-ea926889ede4.png)

2022-08-31 07:14 UTC, merged