Make notifications as an optional
hyperjumptech/monika pull request #86
Opened 2021-03-25 09:07 UTC by ilmiawan

# Monika PR
## What issue is this PR trying to solve
Currently notification is becoming an essential to run Monika. 
Monika's probing should not be dependent to the notifications.

## How this PR solve the issue
Making the notifications as an optional and printout warning to notify the user if notifications has not been set.

## How to test
1. remove notifications from configuration file.
2. run ./bin/run

2021-03-25 09:20 UTC, dennypradipta requested changes

2021-03-25 09:20 UTC, dennypradipta commented on test/utils/alert.test.ts
> +import notifier = require('node-notifier')
Please fix this

2021-03-25 09:24 UTC, ilmiawan commented on test/utils/alert.test.ts
> +import notifier = require('node-notifier')
done

2021-03-26 02:48 UTC, dennypradipta approved these changes

2021-03-26 02:48 UTC, dennypradipta commented on src/utils/validate-config.ts
> +  message: `Notifications config has not been set. We will not be able to notify you when INCIDENT happened!\nPlease refer to Monika documentation for setting the notifications config at https://hype
Change the link to https://hyperjumptech.github.io/monika/guides/notifications

2021-03-26 02:58 UTC, dennypradipta approved these changes

2021-03-26 07:54 UTC, gsukanto approved these changes

2021-03-26 07:54 UTC, merged