Feat: Fake Data in URL
hyperjumptech/monika pull request #862
Opened 2022-08-19 09:29 UTC by dennypradipta

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
This PR closes #857 

## How did you implement / how did you fix it  
1. Add faker
2. Create fakes utils
3. Register the fakes utils as Handlebars helper

## How to test  
Use this config:
```
notifications:
  - id: desktop
    type: desktop

probes:
  - id: '1'
    requests:
      - url: http://github.com?timestamp={{ timestamp }}
      - url: http://github.com?id={{ uuid }}
      - url: http://github.com?timestamp={{ lhohe }}
```

![image](https://user-images.githubusercontent.com/16670475/185589321-73bd3668-4f06-4867-8025-94a35626e905.png)

## Additional Context

As a POC, this will only includes timestamp and uuid

2022-08-22 06:02 UTC, nicnocquee requested changes

2022-08-22 07:21 UTC, dennypradipta commented on src/components/probe/probing.ts
> +  console.log(renderedURL)
That was a mistake for debugging, my bad. Should be fixed

2022-08-22 07:23 UTC, dennypradipta commented
Added more fake data:
```
  countryCode,
  color,
  currency,
  email,
  gender,
  latitude,
  longitude,
  number,
  objectId,
  statusCode,
  timestamp,
  uuid,
```

2022-08-22 08:12 UTC, dennypradipta commented
Updated. Try with this config:
notifications:
  - id: desktop
    type: desktop

probes:
  - id: '1'
    requests:
      - url: http://github.com?alpha={{ alpha }}
      - url: http://github.com?alphaNumeric={{ alphaNumeric }}
      - url: http://github.com?countryCode={{ countryCode }}
      - url: http://github.com?color={{ color }}
      - url: http://github.com?currency={{ currency }}
      - url: http://github.com?email={{ email }}
      - url: http://github.com?fullName={{ fullName }}
      - url: http://github.com?gender={{ gender }}
      - url: http://github.com?latitude={{ latitude }}
      - url: http://github.com?longitude={{ longitude }}
      - url: http://github.com?number={{ number }}
      - url: http://github.com?objectId={{ objectId }}
      - url: http://github.com?statusCode={{ statusCode }}
      - url: http://github.com?timestamp={{ timestamp }}
      - url: http://github.com?uuid={{ uuid }}
      - url: http://github.com?word={{ word }}
      - url: http://github.com?words={{ words }}

Supported fake types:
```
alpha:
alphaNumeric:
countryCode:
color:
currency:
email:
fullName:
gender:
latitude:
lines:
longitude:
number:
objectId:
statusCode:
timestamp:
uuid:
word:
words:
```

For the moment, the props passed to the function are hardcoded. Still figuring out on how to pass the props

2022-08-22 08:46 UTC, dennypradipta commented
Updated. Try with this config:
```
notifications:
  - id: desktop
    type: desktop

probes:
  - id: '0'
    name: '0'
    interval: 10
    requests:
      - url: http://github.com?alpha={{ alpha }}
  - id: '1'
    name: '1'
    interval: 10
    requests:
      - url: http://github.com?alphaNumeric={{ alphaNumeric }}
  - id: '2'
    name: '2'
    interval: 10
    requests:
      - url: http://github.com?countryCode={{ countryCode }}
  - id: '3'
    name: '3'
    interval: 10
    requests:
      - url: http://github.com?color={{ color }}
  - id: '4'
    name: '4'
    interval: 10
    requests:
      - url: http://github.com?currency={{ currency }}
  - id: '5'
    name: '5'
    interval: 10
    requests:
      - url: http://github.com?email={{ email }}
  - id: '6'
    name: '6'
    interval: 10
    requests:
      - url: http://github.com?fullName={{ fullName }}
  - id: '7'
    name: '7'
    interval: 10
    requests:
      - url: http://github.com?gender={{ gender }}
  - id: '8'
    name: '8'
    interval: 10
    requests:
      - url: http://github.com?latitude={{ latitude }}
  - id: '9'
    name: '9'
    interval: 10
    requests:
      - url: http://github.com?lines={{ lines }}
  - id: '10'
    name: '10'
    interval: 10
    requests:
      - url: http://github.com?longitude={{ longitude }}
  - id: '11'
    name: '11'
    interval: 10
    requests:
      - url: http://github.com?number={{ number }}
  - id: '12'
    name: '12'
    interval: 10
    requests:
      - url: http://github.com?objectId={{ objectId }}
  - id: '13'
    name: '13'
    interval: 10
    requests:
      - url: http://github.com?statusCode={{ statusCode }}
  - id: '14'
    name: '14'
    interval: 10
    requests:
      - url: http://github.com?timestamp={{ timestamp }}
  - id: '15'
    name: '15'
    interval: 10
    requests:
      - url: http://github.com?uuid={{ uuid }}
  - id: '16'
    name: '16'
    interval: 10
    requests:
      - url: http://github.com?word={{ word }}
  - id: '17'
    name: '17'
    interval: 10
    requests:
      - url: http://github.com?words={{ words }}
```

![image](https://user-images.githubusercontent.com/16670475/185879207-03801446-68a7-4091-95f4-3ba19a2a179b.png)

Supported fake types:
```
alpha:
alphaNumeric:
countryCode:
color:
currency:
email:
fullName:
gender:
latitude:
lines:
longitude:
number:
objectId:
statusCode:
timestamp:
uuid:
word:
words:
```

For the moment, the props passed to the function are hardcoded. Still figuring out on how to pass the props

2022-08-22 08:52 UTC, dennypradipta commented
Also to be noted, because it is changed in the `probing.ts` file, I think it could also apply to the request body or headers. Kindly check it

2022-08-24 04:49 UTC, dennypradipta commented
Updated. Added `isostring`, dynamic params, and improve docs.

Use this newer config:
```
notifications:
  - id: desktop
    type: desktop

probes:
  - id: '0'
    name: '0'
    interval: 20
    requests:
      - url: http://github.com?alpha={{ alpha }}
      - url: http://github.com?alpha={{ alpha 8 }}
  - id: '1'
    name: '1'
    interval: 20
    requests:
      - url: http://github.com?alphaNumeric={{ alphaNumeric }}
      - url: http://github.com?alphaNumeric={{ alphaNumeric 8 }}
  - id: '2'
    name: '2'
    interval: 10
    requests:
      - url: http://github.com?countryCode={{ countryCode }}
  - id: '3'
    name: '3'
    interval: 10
    requests:
      - url: http://github.com?color={{ color }}
  - id: '4'
    name: '4'
    interval: 10
    requests:
      - url: http://github.com?currency={{ currency }}
  - id: '5'
    name: '5'
    interval: 10
    requests:
      - url: http://github.com?email={{ email }}
  - id: '6'
    name: '6'
    interval: 10
    requests:
      - url: http://github.com?fullName={{ fullName }}
  - id: '7'
    name: '7'
    interval: 10
    requests:
      - url: http://github.com?gender={{ gender }}
  - id: '7.5'
    name: '5'
    interval: 10
    requests:
      - url: http://github.com?isostring={{ isostring }}
  - id: '8'
    name: '8'
    interval: 30
    requests:
      - url: http://github.com?latitude={{ latitude }}
      - url: http://github.com?latitude={{ latitude 40 }}
      - url: http://github.com?latitude={{ latitude 80 80 }}
  - id: '9'
    name: '9'
    interval: 20
    requests:
      - url: http://github.com?lines={{ lines }}
      - url: http://github.com?lines={{ lines 3 }}
  - id: '10'
    name: '10'
    interval: 30
    requests:
      - url: http://github.com?longitude={{ longitude }}
      - url: http://github.com?latitude={{ longitude 40 }}
      - url: http://github.com?latitude={{ longitude 80 80 }}
  - id: '11'
    name: '11'
    interval: 30
    requests:
      - url: http://github.com?number={{ number }}
      - url: http://github.com?number={{ number 8 }}
      - url: http://github.com?number={{ number 8 36 }}
  - id: '12'
    name: '12'
    interval: 10
    requests:
      - url: http://github.com?objectId={{ objectId }}
  - id: '13'
    name: '13'
    interval: 10
    requests:
      - url: http://github.com?statusCode={{ statusCode }}
  - id: '14'
    name: '14'
    interval: 10
    requests:
      - url: http://github.com?timestamp={{ timestamp }}
  - id: '15'
    name: '15'
    interval: 10
    requests:
      - url: http://github.com?uuid={{ uuid }}
  - id: '16'
    name: '16'
    interval: 10
    requests:
      - url: http://github.com?word={{ word }}
  - id: '17'
    name: '17'
    interval: 20
    requests:
      - url: http://github.com?words={{ words }}
      - url: http://github.com?words={{ words 3 }}
```

![image](https://user-images.githubusercontent.com/16670475/186331459-264373b3-8f41-4d76-a90b-872caa71de3d.png)

2022-08-25 07:05 UTC, nicnocquee requested changes

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ isostring }}` returns a date in ISO String format
this is not random date right? but the date of the request? if so, `returns the date of the request sending in ISO format`

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +  e.g `{{ lines }}` returns `Lorem ipsum dolor sit amet`, `{{ lines 2 }}` returns `Commodi non ex voluptatibus quibusdam nisi aliquam dolor nihil. Eos maiores enim praesentium.`
return `lineCount` number of lines of "Lorem ipsum" strings

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ number <min> <max> }}` returns a random number range from `min` to `max`
returns a random integer number between min and max

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ objectId }}` returns a MongoDB ObjectID
returns a random MongoDB ObjectID

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ statusCode }}` returns a status code
returns a random HTTP status code

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ timestamp }}` returns current time in a form of a UNIX timestamp
returns the time of the request sending in UNIX timestamp format

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ uuid }}` returns a UUID
returns a random UUID

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ word }}` returns a word
returns a random English word

2022-08-25 07:05 UTC, nicnocquee commented on docs/src/pages/guides/probes.md
> +- `{{ words <count> }}` returns `<count>` words
returns `count` number of random English words

2022-08-26 07:28 UTC, dennypradipta commented
Updated docs
![image](https://user-images.githubusercontent.com/16670475/186846958-c1202926-47a4-4512-b296-30c2d0b51b41.png)

Along with test
![image](https://user-images.githubusercontent.com/16670475/186847143-b87820bb-737d-4899-aeae-f8ca3acf50e3.png)

2022-08-26 07:36 UTC, nicnocquee approved these changes

2022-08-26 09:41 UTC, sapiderman approved these changes

2022-08-26 09:50 UTC, merged