Refactor the probes
hyperjumptech/monika pull request #863
Opened 2022-08-25 04:19 UTC by sapiderman

# Monika Pull Request (PR)  

## Before PR
1. Probes are mixed between drivers and loggers
2. Difficult to add new probes

## After PR
1. Should be easier to add new probes
2. Code cleaned up
3. Better separation of responsibilities 

## How did you implement / how did you fix it  
1. Refactored the interface between driver and dispatcher
2. Detach drivers from logger and decoding of errors/status codes

## How to test  
1. Run `npm run test` should all pass
2. Use the following test config yaml for local test
```yaml
```
3. Run monika with the above config: `bin/bin-run -c monika.yaml -s -1`

## Screenshot

2022-08-26 06:34 UTC, ilmiawan approved these changes
lgtm

2022-08-26 06:59 UTC, ilmiawan commented on src/components/tcp-request/index.ts
> +  console.log('duration:', duration)
remove console.log

2022-08-26 08:46 UTC, nicnocquee requested changes

2022-08-26 08:46 UTC, nicnocquee commented on src/components/logger/request-log.ts
> +      ${this.request?.method} ${this.request?.url} ${
This code should be 

```javascript
if (this.request?.ping) {
   probeMsg = ...
}
```

because `probeMsg` already set with value in line 104.

2022-08-29 03:22 UTC, sapiderman commented on src/components/tcp-request/index.ts
> +  console.log('duration:', duration)
done... removed debug logs.

2022-08-29 06:12 UTC, nicnocquee approved these changes

2022-08-29 06:12 UTC, merged