Update JSON scheam for redis/postgres requests
hyperjumptech/monika pull request #876
Opened 2022-09-07 05:33 UTC by sapiderman

# Monika Pull Request (PR)  

## What feature/issue does this PR add  
1. Part of #858 
2. Part of #859 
3. Update json schema for the new probe requests

## How did you implement / how did you fix it  
1.  Add entries for redis and postgres requests

## How to test  
1. Use the monika-config.schema.json in this pr
2. Create a config.yml file something like below:
```yaml
probes:
  - id: checking-redis
    name: ping redis
    alerts:
      - query: response.status != 200
        message: redis not available
    incidentThreshold: 2
    recoveryThreshold: 2
    redis:
      - host: 172.17.0.1 // mising port

  - id: checking-postgress
    name: ensure postgress is alive
    alerts:
      - query: response.status != 200
        message: redis not available
    incidentThreshold: 2
    recoveryThreshold: 2
    redis:
      - host: 172.2.1.1
        host: 1.2.3.4 // non unique error
        port: 5432

notifications:
  - id: desktop-01
    type: desktop
```
3.  You should get multiple errors from the schema processor

## Screenshot

2022-09-09 07:38 UTC, dennypradipta approved these changes

2022-09-13 15:53 UTC, nicnocquee requested changes

2022-09-13 15:53 UTC, nicnocquee commented on monika-config-schema.json
> +            "description": "The host address of the redis",
The hostname or IP address of redis server

2022-09-13 15:53 UTC, nicnocquee commented on monika-config-schema.json
> +            "default": "mypassword"
is it possible for the default to be simply empty string `""`

2022-09-13 15:53 UTC, nicnocquee commented on monika-config-schema.json
> +            "default": "myuser"
is it possible for the default to be simply empty string `""`

2022-09-14 07:20 UTC, nicnocquee approved these changes

2022-09-14 07:23 UTC, merged